In [2]:
#Assignments

#Assignment 1: Student Pass/Fail Prediction

#Dataset Columns:
#- Study_Hours
#- Attendance_Percentage
#- Pass (0/1)

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [8]:
import seaborn as sns

In [6]:
import matplotlib.pyplot as plt

In [24]:
#1. Create 50–100 records.
#2. Load dataset using pandas.

df=pd.read_csv("students_data.csv")
df

    Study_Hours  Attendance  Pass
0             1          45     0
1             2          50     0
2             3          55     0
3             4          60     0
4             5          65     1
..          ...         ...   ...
94            5          71     1
95            6          77     1
96            7          83     1
97            8          90     1
98            2          49     0

[99 rows x 3 columns]

In [25]:
print(df.head(10))

   Study_Hours  Attendance  Pass
0            1          45     0
1            2          50     0
2            3          55     0
3            4          60     0
4            5          65     1
5            6          70     1
6            7          75     1
7            8          80     1
8            2          52     0
9            3          58     0

In [26]:
X=df[["Study_Hours","Attendance"]]
y=df["Pass"]

In [27]:
X

    Study_Hours  Attendance
0             1          45
1             2          50
2             3          55
3             4          60
4             5          65
..          ...         ...
94            5          71
95            6          77
96            7          83
97            8          90
98            2          49

[99 rows x 2 columns]

In [28]:
y

0     0
1     0
2     0
3     0
4     1
     ..
94    1
95    1
96    1
97    1
98    0
Name: Pass, Length: 99, dtype: int64

In [48]:
#3. Split data into X and y.
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [31]:
X_train

    Study_Hours  Attendance
49            5          71
70            4          66
68            2          53
15            1          40
39            3          53
..          ...         ...
60            1          43
71            5          73
14            8          85
92            3          59
51            7          83

[79 rows x 2 columns]

In [32]:
X_test

    Study_Hours  Attendance
62            3          55
40            4          61
95            6          77
18            4          66
97            8          90
84            3          54
64            5          70
42            6          73
10            4          62
0             1          45
31            2          50
76            2          50
47            3          59
26            5          72
44            8          86
4             5          65
22            8          88
12            6          72
88            7          78
73            7          85

In [49]:
#4. Train Logistic Regression.
from sklearn.linear_model import LogisticRegression

In [38]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [40]:
y_pred = model.predict(X_test)

In [59]:
#5. Predict Pass/Fail.
new_student=[[6,80]]
prediction=model.predict(new_student)

if prediction[0]==1:
    print("Pass")
else:
    print("Fail")

Pass

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [60]:
df.shape

(99, 3)

In [62]:
df["Pass"]=df["Pass"].replace({
    0:"Fail",
    1:"Pass"
})
df

    Study_Hours  Attendance  Pass
0             1          45  Fail
1             2          50  Fail
2             3          55  Fail
3             4          60  Fail
4             5          65  Pass
..          ...         ...   ...
94            5          71  Pass
95            6          77  Pass
96            7          83  Pass
97            8          90  Pass
98            2          49  Fail

[99 rows x 3 columns]

In [50]:
#6. Calculate Accuracy Score.
from sklearn.metrics import accuracy_score

In [47]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy*100,"%")

95.0 %

In [56]:
print(df.shape)

(99, 3)

In [ ]:
#Assignment 2: Loan Approval Prediction
#Dataset Columns:
#- Income
#- Credit_Score
#- Loan_Approved (0/1)

In [ ]:
#1. Create 100 records.
df=pd.read_csv("")
df