In [ ]:
#Assignment 2: Loan Approval Prediction

#Dataset Columns:
#- Income
#- Credit_Score
#- Loan_Approved (0/1)

In [3]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
import seaborn as sns

In [7]:
import matplotlib.pyplot as plt

In [9]:
#1. Create 100 records.
df=pd.read_csv("Loan_Approval.csv")
df

     Income  Credit_Score Loan_Approval
0   25000.0           520            No
1   28000.0           540            No
2   30000.0           560            No
3   32000.0           570            No
4   35000.0           580            No
..      ...           ...           ...
95      NaN           692           Yes
96      NaN           702           Yes
97      NaN           712           Yes
98      NaN           722           Yes
99      NaN           732           Yes

[100 rows x 3 columns]

In [10]:
df.shape

(100, 3)

In [27]:
df.head(10)

    Income  Credit_Score Loan_Approval
0  25000.0           520            No
1  28000.0           540            No
2  30000.0           560            No
3  32000.0           570            No
4  35000.0           580            No
5  37000.0           590           yes
6  40000.0           600            No
7  42000.0           610            No
8  45000.0           620           yes
9  47000.0           630            No

In [37]:
df.tail(10)

     Income  Credit_Score Loan_Approval
90  50500.0           642            No
91    525.0           652            No
92      NaN           662           Yes
93      NaN           672           Yes
94      NaN           682           Yes
95      NaN           692           Yes
96      NaN           702           Yes
97      NaN           712           Yes
98      NaN           722           Yes
99      NaN           732           Yes

In [40]:
df["Income"]=df["Income"].fillna(df["Income"].mean())
df

          Income  Credit_Score Loan_Approval
0   25000.000000           520            No
1   28000.000000           540            No
2   30000.000000           560            No
3   32000.000000           570            No
4   35000.000000           580            No
..           ...           ...           ...
95  68663.315217           692           Yes
96  68663.315217           702           Yes
97  68663.315217           712           Yes
98  68663.315217           722           Yes
99  68663.315217           732           Yes

[100 rows x 3 columns]

In [41]:
X=df[["Income","Credit_Score"]]
y=df["Loan_Approval"]

In [42]:
X

          Income  Credit_Score
0   25000.000000           520
1   28000.000000           540
2   30000.000000           560
3   32000.000000           570
4   35000.000000           580
..           ...           ...
95  68663.315217           692
96  68663.315217           702
97  68663.315217           712
98  68663.315217           722
99  68663.315217           732

[100 rows x 2 columns]

In [43]:
y

0      No
1      No
2      No
3      No
4      No
     ...
95    Yes
96    Yes
97    Yes
98    Yes
99    Yes
Name: Loan_Approval, Length: 100, dtype: object

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
#split data into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [46]:
X_train

           Income  Credit_Score
55   63000.000000           695
88   45500.000000           622
26   90000.000000           800
42   31000.000000           565
69   99000.000000           835
..            ...           ...
60   76000.000000           745
71  103000.000000           855
14   60000.000000           680
92   68663.315217           662
51   53000.000000           655

[80 rows x 2 columns]

In [47]:
X_test

      Income  Credit_Score
83   34000.0           572
53   59000.0           675
70  101000.0           845
45   39000.0           595
44   36000.0           585
39  118000.0           930
22   80000.0           760
80   27000.0           525
10   50000.0           640
0    25000.0           520
18   70000.0           720
30  100000.0           840
73  107000.0           875
33  106000.0           870
90   50500.0           642
4    35000.0           580
76  113000.0           905
77  115000.0           915
12   55000.0           660
31  102000.0           850

In [2]:
#2. Train Logistic Regression.
from sklearn.linear_model import LogisticRegression

In [49]:

model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [50]:
#3. Predict loan approval.
y_pred = model.predict(X_test)
print("Predicted Values")
print(y_pred)

Predicted Values
['No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes']

In [52]:
#4. Generate Confusion Matrix.
from sklearn.metrics import confusion_matrix,accuracy_score

In [53]:
cm=confusion_matrix(y_test,y_pred)
print("\nConfusion Matrix:")
print(cm)

Confusion Matrix:
[[ 8  1]
 [ 0 11]]

In [54]:
#5. Calculate Accuracy.
from sklearn.metrics import confusion_matrix,accuracy_score

In [55]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.95