In [11]:
#Assignment 3: Customer Purchase Prediction

#Dataset Columns:
#- Age
#- Monthly_Income
#- Purchased (0/1)

In [12]:
import numpy as np

In [13]:
import pandas as pd

In [14]:
import matplotlib.pyplot as plt

In [15]:
import seaborn as sns

In [16]:
#1. Create 80–100 records.
df=pd.read_csv("Customer_data.csv")
df

    Age  Monthly_Income  Purchased
0    22           25000          0
1    25           30000          0
2    28           35000          0
3    30           40000          0
4    32           45000          1
..  ...             ...        ...
95   54           89000          1
96   55           91000          1
97   56           93000          1
98   57           95000          1
99   52           85000          0

[100 rows x 3 columns]

In [17]:
df.shape

(100, 3)

In [18]:
df.head(10)

   Age  Monthly_Income  Purchased
0   22           25000          0
1   25           30000          0
2   28           35000          0
3   30           40000          0
4   32           45000          1
5   35           50000          1
6   40           60000          1
7   45           70000          1
8   50           80000          1
9   23           27000          0

In [19]:
df.tail(10)

    Age  Monthly_Income  Purchased
90   49           79000          1
91   50           81000          1
92   51           83000          1
93   52           85000          1
94   53           87000          1
95   54           89000          1
96   55           91000          1
97   56           93000          1
98   57           95000          1
99   52           85000          0

In [20]:
df.describe()

              Age  Monthly_Income   Purchased
count  100.000000      100.000000  100.000000
mean    37.800000    56020.000000    0.640000
std     10.415606    20891.243151    0.482418
min     20.000000    20000.000000    0.000000
25%     29.000000    37750.000000    0.000000
50%     37.500000    55000.000000    1.000000
75%     47.000000    74250.000000    1.000000
max     57.000000    95000.000000    1.000000

In [21]:
df.isnull().sum()

Age               0
Monthly_Income    0
Purchased         0
dtype: int64

In [22]:
#Input Output
X=df[["Age","Monthly_Income"]]
y=df["Purchased"]

In [23]:
X

    Age  Monthly_Income
0    22           25000
1    25           30000
2    28           35000
3    30           40000
4    32           45000
..  ...             ...
95   54           89000
96   55           91000
97   56           93000
98   57           95000
99   52           85000

[100 rows x 2 columns]

In [24]:
y

0     0
1     0
2     0
3     0
4     1
     ..
95    1
96    1
97    1
98    1
99    0
Name: Purchased, Length: 100, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
#split data into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [27]:
X_train

    Age  Monthly_Income
55   50           80000
88   47           75000
26   21           22000
42   37           54000
69   28           37000
..  ...             ...
60   55           90000
71   30           41000
14   38           55000
92   51           83000
51   46           72000

[80 rows x 2 columns]

In [28]:
X_test

    Age  Monthly_Income
83   42           65000
53   48           76000
70   29           39000
45   40           60000
44   39           58000
39   34           48000
22   39           58000
80   39           59000
10   26           32000
0    22           25000
18   24           29000
30   25           30000
73   32           45000
33   28           36000
90   49           79000
4    32           45000
76   35           51000
77   36           53000
12   31           42000
31   26           32000

In [29]:
#2. Train Logistic Regression.
from sklearn.linear_model import LogisticRegression

In [30]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [31]:
#3. Predict customer purchase.
Y_pred=model.predict(X_test)
print("predicted values")
print(Y_pred)

predicted values
[1 1 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 1 0 0]

In [32]:
X_test

    Age  Monthly_Income
83   42           65000
53   48           76000
70   29           39000
45   40           60000
44   39           58000
39   34           48000
22   39           58000
80   39           59000
10   26           32000
0    22           25000
18   24           29000
30   25           30000
73   32           45000
33   28           36000
90   49           79000
4    32           45000
76   35           51000
77   36           53000
12   31           42000
31   26           32000

In [33]:
#4. Evaluate model performance.
from sklearn.metrics import accuracy_score

In [34]:
accuracy=accuracy_score(y_test,Y_pred)
print(accuracy)

0.85

In [35]:
#confusion
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,Y_pred)
print(cm)

[[ 7  0]
 [ 3 10]]