In [1]:
#Assignment 5: Diabetes Risk Prediction

#Dataset Columns:
#- Age
#- BMI
#- Blood_Sugar
#- Diabetes (0/1)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pypylot as plt

In [4]:
#1. Create 100 records.
df=pd.read_csv("Diabetes_data.csv")
df

    Age  BMI  Blood_Sugar  Diabetes
0    25   23           85         0
1    32   24           92         0
2    45   29          110         1
3    50   31          145         1
4    28   23           88         0
..  ...  ...          ...       ...
95   58   35          164         1
96   31   25           94         0
97   42   29          118         1
98   50   31          143         1
99   61   35          173         1

[100 rows x 4 columns]

In [5]:
df.head()

   Age  BMI  Blood_Sugar  Diabetes
0   25   23           85         0
1   32   24           92         0
2   45   29          110         1
3   50   31          145         1
4   28   23           88         0

In [6]:
df.tail()

    Age  BMI  Blood_Sugar  Diabetes
95   58   35          164         1
96   31   25           94         0
97   42   29          118         1
98   50   31          143         1
99   61   35          173         1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          100 non-null    int64
 1   BMI          100 non-null    int64
 2   Blood_Sugar  100 non-null    int64
 3   Diabetes     100 non-null    int64
dtypes: int64(4)
memory usage: 3.3 KB

In [13]:
df.describe().sum()

Age            367.946559
BMI            277.429830
Blood_Sugar    884.702564
Diabetes       104.067570
dtype: float64

In [9]:
df.isnull().sum()

Age            0
BMI            0
Blood_Sugar    0
Diabetes       0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
df.shape

(100, 4)

In [14]:
df.describe()

              Age        BMI  Blood_Sugar   Diabetes
count  100.000000  100.00000   100.000000  100.00000
mean    43.010000   28.94000   124.440000    0.57000
std     11.686559    4.23983    30.512564    0.49757
min     22.000000   21.00000    80.000000    0.00000
25%     32.750000   25.00000    97.000000    0.00000
50%     42.500000   29.00000   118.500000    1.00000
75%     53.000000   32.25000   150.250000    1.00000
max     63.000000   37.00000   184.000000    1.00000

In [15]:
#Input Output
X=df[["Age","BMI","Blood_Sugar"]]
y=df["Diabetes"]

In [16]:
X

    Age  BMI  Blood_Sugar
0    25   23           85
1    32   24           92
2    45   29          110
3    50   31          145
4    28   23           88
..  ...  ...          ...
95   58   35          164
96   31   25           94
97   42   29          118
98   50   31          143
99   61   35          173

[100 rows x 3 columns]

In [17]:
y

0     0
1     0
2     1
3     1
4     0
     ..
95    1
96    0
97    1
98    1
99    1
Name: Diabetes, Length: 100, dtype: int64

In [18]:
#Split data into training and testing
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
X_train

    Age  BMI  Blood_Sugar
55   36   27          106
88   27   23           86
26   47   30          130
42   35   26          100
69   39   28          109
..  ...  ...          ...
60   26   22           83
71   53   33          149
14   41   28          115
92   29   25           90
51   34   26          101

[80 rows x 3 columns]

In [22]:
X_test

    Age  BMI  Blood_Sugar
83   57   34          162
53   55   33          154
70   47   31          136
45   30   25           96
44   54   32          152
39   57   34          160
22   44   29          118
80   24   23           85
10   27   22           84
0    25   23           85
18   58   35          165
30   24   22           82
73   40   28          119
33   51   32          140
90   49   31          139
4    28   23           88
76   32   24           92
77   43   30          124
12   48   31          135
31   37   27          104

In [23]:
#2. Train Logistic Regression.
from sklearn.linear_model import LogisticRegression

In [24]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [25]:
#3. Predict diabetes risk.
Y_pred=model.predict(X_test)
print("predicted values")
print(Y_pred)

predicted values
[1 1 1 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0]

In [26]:
Y_pred

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0])

In [27]:
y_test

83    1
53    1
70    1
45    0
44    1
39    1
22    1
80    0
10    0
0     0
18    1
30    0
73    1
33    1
90    1
4     0
76    0
77    1
12    1
31    0
Name: Diabetes, dtype: int64

In [28]:
#4. Display Accuracy, Precision, Recall, and Confusion Matrix.

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
#Accuracy
accuracy=accuracy_score(y_test,Y_pred)
print(accuracy)

1.0

In [40]:
#Precision
from sklearn.metrics import precision_score

In [41]:
precision=precision_score(y_test,Y_pred)
print(precision)

1.0

In [44]:
#Recall
from sklearn.metrics import recall_score

In [46]:
recall=recall_score(Y_pred,y_test)
print(recall)

1.0

In [42]:
#Confusion Matrix.
from sklearn.metrics import confusion_matrix

In [43]:
cm=confusion_matrix(y_test,Y_pred)
print(cm)

[[ 8  0]
 [ 0 12]]